// ------------------- Question Bank (45 Questions) -------------------
let questions = [
  // 1-15 (original)
  { question: "What is the capital of France?", answers: ["Berlin", "London", "Paris", "Madrid"], correct: 2 },
  { question: "Which planet is known as the Red Planet?", answers: ["Earth", "Mars", "Jupiter", "Venus"], correct: 1 },
  { question: "Who wrote 'Hamlet'?", answers: ["Shakespeare", "Tolkien", "Dickens", "Austen"], correct: 0 },
  { question: "Which gas is most abundant in the Earth's atmosphere?", answers: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], correct: 2 },
  { question: "What is the square root of 144?", answers: ["10", "12", "14", "16"], correct: 1 },
  { question: "Which ocean is the largest?", answers: ["Atlantic", "Indian", "Arctic", "Pacific"], correct: 3 },
  { question: "How many continents are there?", answers: ["5", "6", "7", "8"], correct: 2 },
  { question: "Who painted the Mona Lisa?", answers: ["Van Gogh", "Picasso", "Da Vinci", "Michelangelo"], correct: 2 },
  { question: "Which element has the chemical symbol 'O'?", answers: ["Gold", "Oxygen", "Iron", "Hydrogen"], correct: 1 },
  { question: "What is the smallest prime number?", answers: ["0", "1", "2", "3"], correct: 2 },
  { question: "Which is the longest river in the world?", answers: ["Amazon", "Nile", "Yangtze", "Ganges"], correct: 1 },
  { question: "Which country hosted the 2020 Olympics?", answers: ["China", "Japan", "UK", "USA"], correct: 1 },
  { question: "What is H2O commonly known as?", answers: ["Salt", "Water", "Oxygen", "Hydrogen"], correct: 1 },
  { question: "Which language is primarily spoken in Brazil?", answers: ["Spanish", "Portuguese", "French", "English"], correct: 1 },
  { question: "Which is the fastest land animal?", answers: ["Lion", "Cheetah", "Leopard", "Tiger"], correct: 1 },

  // 16-60 (extra general knowledge)
  { question: "In which year did World War II end?", answers: ["1940", "1945", "1950", "1939"], correct: 1 },
  { question: "Who developed the theory of relativity?", answers: ["Newton", "Einstein", "Tesla", "Galileo"], correct: 1 },
  { question: "Which country is known as the Land of the Rising Sun?", answers: ["India", "Japan", "China", "Thailand"], correct: 1 },
  { question: "Which metal is liquid at room temperature?", answers: ["Iron", "Mercury", "Sodium", "Lead"], correct: 1 },
  { question: "What is the largest mammal in the world?", answers: ["Elephant", "Blue Whale", "Shark", "Giraffe"], correct: 1 },
  { question: "What currency is used in the USA?", answers: ["Euro", "Dollar", "Pound", "Peso"], correct: 1 },
  { question: "Which organ pumps blood in the human body?", answers: ["Brain", "Lungs", "Heart", "Liver"], correct: 2 },
  { question: "Who discovered gravity?", answers: ["Galileo", "Einstein", "Newton", "Kepler"], correct: 2 },
  { question: "What is the capital of India?", answers: ["Mumbai", "Delhi", "Kolkata", "Chennai"], correct: 1 },
  { question: "Which is the tallest mountain in the world?", answers: ["K2", "Mount Everest", "Kangchenjunga", "Nanda Devi"], correct: 1 },
  { question: "What is the national sport of Japan?", answers: ["Sumo", "Cricket", "Baseball", "Football"], correct: 0 },
  { question: "What is 15 × 15?", answers: ["200", "220", "225", "230"], correct: 2 },
  { question: "Who invented the telephone?", answers: ["Alexander Graham Bell", "Edison", "Tesla", "Marconi"], correct: 0 },
  { question: "Which country gifted the Statue of Liberty to the USA?", answers: ["France", "UK", "Germany", "Canada"], correct: 0 },
  { question: "Which blood group is known as universal donor?", answers: ["A", "B", "O negative", "AB+"], correct: 2 },
  { question: "How many states are there in India?", answers: ["27", "28", "29", "30"], correct: 1 },
  { question: "Who was the first man on the moon?", answers: ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "John Glenn"], correct: 0 },
  { question: "Which is the hardest natural substance?", answers: ["Gold", "Diamond", "Iron", "Platinum"], correct: 1 },
  { question: "What is the chemical symbol for Gold?", answers: ["Ag", "Au", "Gd", "Go"], correct: 1 },
  { question: "What is the freezing point of water?", answers: ["0°C", "10°C", "100°C", "32°C"], correct: 0 },
  { question: "Which continent is the Sahara Desert located in?", answers: ["Asia", "Africa", "Australia", "South America"], correct: 1 },
  { question: "What is the capital of Australia?", answers: ["Sydney", "Melbourne", "Canberra", "Perth"], correct: 2 },
  { question: "Which animal is known as the Ship of the Desert?", answers: ["Horse", "Camel", "Donkey", "Elephant"], correct: 1 },
  { question: "Which gas do humans exhale?", answers: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], correct: 2 },
  { question: "What is the national bird of India?", answers: ["Eagle", "Peacock", "Sparrow", "Crow"], correct: 1 },
  { question: "Which festival is known as the festival of lights?", answers: ["Holi", "Diwali", "Eid", "Christmas"], correct: 1 },
  { question: "Which is the smallest country in the world?", answers: ["Monaco", "Vatican City", "Malta", "San Marino"], correct: 1 },
  { question: "Which is the largest desert in the world?", answers: ["Thar", "Sahara", "Antarctica", "Gobi"], correct: 2 },
  { question: "Which is the largest planet in our Solar System?", answers: ["Earth", "Saturn", "Jupiter", "Neptune"], correct: 2 },
  { question: "What is the boiling point of water?", answers: ["50°C", "100°C", "150°C", "200°C"], correct: 1 },
  { question: "Which country has the largest population in the world?", answers: ["USA", "India", "China", "Russia"], correct: 2 },
  { question: "Which is the smallest planet in our Solar System?", answers: ["Mercury", "Mars", "Venus", "Pluto"], correct: 0 },
  { question: "What is the national currency of Japan?", answers: ["Yuan", "Yen", "Won", "Dollar"], correct: 1 },
  { question: "Who painted the ceiling of the Sistine Chapel?", answers: ["Leonardo da Vinci", "Michelangelo", "Raphael", "Donatello"], correct: 1 },
  { question: "Which city is known as the City of Love?", answers: ["Venice", "Paris", "Rome", "New York"], correct: 1 },
  { question: "What is the chemical symbol for Silver?", answers: ["Si", "Ag", "Au", "S"], correct: 1 },
  { question: "How many bones are there in an adult human body?", answers: ["206", "210", "215", "200"], correct: 0 },
  { question: "Which country is famous for the Great Wall?", answers: ["India", "China", "Egypt", "Mexico"], correct: 1 },
  { question: "What is the capital of Canada?", answers: ["Toronto", "Vancouver", "Ottawa", "Montreal"], correct: 2 },
  { question: "Which gas is essential for breathing?", answers: ["Carbon Dioxide", "Nitrogen", "Oxygen", "Helium"], correct: 2 },
  { question: "Which scientist proposed the three laws of motion?", answers: ["Einstein", "Galileo", "Newton", "Tesla"], correct: 2 },
  { question: "What is the main source of energy for Earth?", answers: ["The Moon", "The Sun", "The Stars", "Volcanoes"], correct: 1 },
  { question: "Which Indian festival is known as the festival of colors?", answers: ["Diwali", "Holi", "Eid", "Baisakhi"], correct: 1 },
  { question: "What is the capital of Russia?", answers: ["Moscow", "St. Petersburg", "Kazan", "Kiev"], correct: 0 },
  { question: "Which is the tallest animal in the world?", answers: ["Elephant", "Camel", "Giraffe", "Horse"], correct: 2 }
];